In [1]:
import pandas as pd

In [4]:
pd.options.display.max_rows = 10
pd.options.display.max_columns = 1000

In [5]:
dataSet = pd.read_csv("insurance.csv")
dataSet

age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
X = dataSet[["age","gender","bmi","children","smoker","region"]]
X

age  gender     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [11]:
y = dataSet["charges"]

In [12]:
pd.get_dummies(X, drop_first = True)

age     bmi  children  gender_male  smoker_yes  region_northwest  \
0      19  27.900         0            0           1                 0   
1      18  33.770         1            1           0                 0   
2      28  33.000         3            1           0                 0   
3      33  22.705         0            1           0                 1   
4      32  28.880         0            1           0                 1   
...   ...     ...       ...          ...         ...               ...   
1333   50  30.970         3            1           0                 1   
1334   18  31.920         0            0           0                 0   
1335   18  36.850         0            0           0                 0   
1336   21  25.800         0            0           0                 0   
1337   61  29.070         0            0           1                 1   

      region_southeast  region_southwest  
0                    0                 1  
1                    1                 0  
2                    1                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
1333                 0                 0  
1334                 0                 0  
1335                 1                 0  
1336                 0                 1  
1337                 0                 0  

[1338 rows x 8 columns]

In [14]:
X = pd.get_dummies(X,  drop_first = True)
X

age     bmi  children  gender_male  smoker_yes  region_northwest  \
0      19  27.900         0            0           1                 0   
1      18  33.770         1            1           0                 0   
2      28  33.000         3            1           0                 0   
3      33  22.705         0            1           0                 1   
4      32  28.880         0            1           0                 1   
...   ...     ...       ...          ...         ...               ...   
1333   50  30.970         3            1           0                 1   
1334   18  31.920         0            0           0                 0   
1335   18  36.850         0            0           0                 0   
1336   21  25.800         0            0           0                 0   
1337   61  29.070         0            0           1                 1   

      region_southeast  region_southwest  
0                    0                 1  
1                    1                 0  
2                    1                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
1333                 0                 0  
1334                 0                 0  
1335                 1                 0  
1336                 0                 1  
1337                 0                 0  

[1338 rows x 8 columns]

In [69]:
from sklearn import model_selection

In [70]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y.values, 
                                    test_size = 0.3 , random_state = 1)

In [71]:
X.values
y.values

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [72]:
type(X.values), type(X), type(X_train)

(numpy.ndarray, pandas.core.frame.DataFrame, numpy.ndarray)

In [73]:
X_train.shape, X_test.shape, X.shape

((936, 8), (402, 8), (1338, 8))

In [74]:
X.values

array([[19.  , 27.9 ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [18.  , 33.77,  1.  , ...,  0.  ,  1.  ,  0.  ],
       [28.  , 33.  ,  3.  , ...,  0.  ,  1.  ,  0.  ],
       ...,
       [18.  , 36.85,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [21.  , 25.8 ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [61.  , 29.07,  0.  , ...,  1.  ,  0.  ,  0.  ]])

In [75]:
X_train

array([[50.  , 26.41,  0.  , ...,  1.  ,  0.  ,  0.  ],
       [21.  , 26.4 ,  1.  , ...,  0.  ,  0.  ,  1.  ],
       [25.  , 26.22,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [51.  , 34.96,  2.  , ...,  0.  ,  0.  ,  0.  ],
       [40.  , 22.22,  2.  , ...,  0.  ,  1.  ,  0.  ],
       [57.  , 27.94,  1.  , ...,  0.  ,  1.  ,  0.  ]])

In [76]:
X_test

array([[19.   , 35.53 ,  0.   , ...,  1.   ,  0.   ,  0.   ],
       [57.   , 31.54 ,  0.   , ...,  1.   ,  0.   ,  0.   ],
       [51.   , 37.   ,  0.   , ...,  0.   ,  0.   ,  1.   ],
       ...,
       [20.   , 28.785,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [26.   , 27.06 ,  0.   , ...,  0.   ,  1.   ,  0.   ],
       [49.   , 27.1  ,  1.   , ...,  0.   ,  0.   ,  1.   ]])

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [79]:
X_train_std = scaler.transform(X_train)

In [80]:
X_test_std = scaler.transform(X_test)

In [81]:
pd.DataFrame(X_train_std)

0         1         2         3         4         5         6  \
0    0.797152 -0.702114 -0.904002  0.976766 -0.509664  1.788102 -0.600387   
1   -1.271085 -0.703758 -0.085679 -1.023787 -0.509664 -0.559252 -0.600387   
2   -0.985811 -0.733340 -0.904002  0.976766 -0.509664 -0.559252 -0.600387   
3    0.797152 -0.414510  1.550967 -1.023787 -0.509664 -0.559252  1.665591   
4    0.868471  1.482037 -0.085679  0.976766 -0.509664 -0.559252 -0.600387   
..        ...       ...       ...       ...       ...       ...       ...   
931  1.510338 -0.292894 -0.904002  0.976766 -0.509664 -0.559252 -0.600387   
932 -0.914493 -0.218117  0.732644 -1.023787 -0.509664 -0.559252 -0.600387   
933  0.868471  0.703039  0.732644 -1.023787  1.962076 -0.559252 -0.600387   
934  0.083967 -1.390722  0.732644 -1.023787  1.962076 -0.559252  1.665591   
935  1.296382 -0.450666 -0.085679  0.976766 -0.509664 -0.559252  1.665591   

            7  
0   -0.587220  
1    1.702939  
2   -0.587220  
3   -0.587220  
4    1.702939  
..        ...  
931  1.702939  
932 -0.587220  
933 -0.587220  
934 -0.587220  
935 -0.587220  

[936 rows x 8 columns]

In [82]:
type(pd.DataFrame(X_train_std))
pd.DataFrame(X_train_std).describe()

0             1             2             3             4  \
count  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02  9.360000e+02   
mean  -9.014631e-17  3.054122e-15 -1.869795e-16 -1.119712e-16  1.775645e-16   
std    1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00  1.000535e+00   
min   -1.485041e+00 -2.419524e+00 -9.040023e-01 -1.023787e+00 -5.096643e-01   
25%   -9.144925e-01 -7.247116e-01 -9.040023e-01 -1.023787e+00 -5.096643e-01   
50%   -5.867016e-02 -3.076297e-02 -8.567913e-02  9.767656e-01 -5.096643e-01   
75%    8.684707e-01  6.631857e-01  7.326440e-01  9.767656e-01 -5.096643e-01   
max    1.795612e+00  3.689196e+00  3.187613e+00  9.767656e-01  1.962076e+00   

                  5             6             7  
count  9.360000e+02  9.360000e+02  9.360000e+02  
mean   1.560955e-16  1.518254e-17  2.436323e-16  
std    1.000535e+00  1.000535e+00  1.000535e+00  
min   -5.592522e-01 -6.003875e-01 -5.872202e-01  
25%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
50%   -5.592522e-01 -6.003875e-01 -5.872202e-01  
75%   -5.592522e-01  1.665591e+00  1.702939e+00  
max    1.788102e+00  1.665591e+00  1.702939e+00

In [83]:
from sklearn import linear_model

In [84]:
est = linear_model.LinearRegression()

In [85]:
est.fit(X_train_std, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [86]:
est.coef_

array([3528.98273114, 1961.65520818,  421.55016415, -141.35911014,
       9733.78688309, -129.54588605, -414.54148288, -379.09534369])

In [87]:
est.intercept_

13276.698553898497

In [88]:
pd.DataFrame({"features": X.columns, "theta": est.coef_})

features        theta
0               age  3528.982731
1               bmi  1961.655208
2          children   421.550164
3       gender_male  -141.359110
4        smoker_yes  9733.786883
5  region_northwest  -129.545886
6  region_southeast  -414.541483
7  region_southwest  -379.095344